title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: link
            field:
              type: link
              display: Link
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
          -
            handle: description
            field:
              type: textarea
              display: Description
          -
            handle: technologies
            field:
              type: replicator
              display: Technologies
              sets:
                new_set_group:
                  display: 'New Set Group'
                  sets:
                    new_set:
                      display: 'New Set'
                      fields:
                        -
                          handle: title
                          field:
                            type: text
                            display: Title
                        -
                          handle: icon_svg
                          field:
                            type: code
                            display: 'Icon SVG'
                        -
                          handle: icon_img
                          field:
                            container: assets
                            type: assets
                            display: 'Icon Image'
      -
        display: 'New Section'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
